### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by khda91** [pkev321/task_4#1]
https://github.com/pkev321/task_4/blob/c03b1475a6f270312a6adef83ba430c0ae2c1bdc/src/ru/levelup/pavel_kustov/qa/homework1/task4/Main.java#L58

Какими способами можно ещё проверить, что треугольник является прямоугольным?

**Comment by pkev321** [comment]
Понял.
Можно было  просто проверить выполнения условия: 
```
pow(side[0], 2) + pow(side[1], 2) == pow(side[2], 2)
```

**Comment by khda91** [comment]
Это один из вариантов. 
Вопрос закрываю)
